const mockProducts = [
    {
        id: 1,
        title: 'MacBook Pro 14寸 M2 Pro',
        description: '2023款 MacBook Pro，14寸，M2 Pro芯片，16GB内存，512GB SSD，成色99新，带原装充电器。',
        price: 12999,
        category_id: 2,
        status: 'on_sale',
        images: JSON.stringify(['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400']),
        contact_phone: '138****8888',
        contact_wechat: 'macbook_seller',
        view_count: 128,
        favorite_count: 23,
        user_id: 1,
        created_at: '2024-01-15 10:30:00',
        username: '科技达人',
        nickname: '小明',
        avatar: '',
        category_name: '💻 数码产品'
    },
    {
        id: 2,
        title: '高等数学教材 同济大学第七版',
        description: '全新未拆封，考研必备教材，附赠习题册和答案解析。',
        price: 45,
        category_id: 1,
        status: 'on_sale',
        images: JSON.stringify(['https://images.unsplash.com/photo-1457369450288-ac5ce068fe85?w=400']),
        contact_phone: '139****6666',
        contact_wechat: 'textbook_seller',
        view_count: 89,
        favorite_count: 12,
        user_id: 2,
        created_at: '2024-01-14 15:20:00',
        username: '学霸小李',
        nickname: '小李',
        avatar: '',
        category_name: '📚 教材教辅'
    },
    {
        id: 3,
        title: 'iPhone 15 Pro Max 256GB',
        description: '蓝色钛金属，使用半年，电池健康98%，无磕碰划痕，全套包装齐全。',
        price: 8999,
        category_id: 3,
        status: 'on_sale',
        images: JSON.stringify(['https://images.unsplash.com/photo-1696004438921-89446b18211d?w=400']),
        contact_phone: '137****9999',
        contact_wechat: 'iphone_seller',
        view_count: 256,
        favorite_count: 45,
        user_id: 3,
        created_at: '2024-01-13 09:10:00',
        username: '数码玩家',
        nickname: '小华',
        avatar: '',
        category_name: '📱 手机平板'
    },
    {
        id: 4,
        title: '捷安特ATX777山地自行车',
        description: '27速，碟刹，铝合金车架，适合校园通勤和轻度越野，成色9成新。',
        price: 850,
        category_id: 6,
        status: 'on_sale',
        images: JSON.stringify(['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400']),
        contact_phone: '136****7777',
        contact_wechat: 'bike_seller',
        view_count: 67,
        favorite_count: 8,
        user_id: 4,
        created_at: '2024-01-12 14:45:00',
        username: '骑行爱好者',
        nickname: '阿强',
        avatar: '',
        category_name: '🚲 出行工具'
    },
    {
        id: 5,
        title: '索尼WH-1000XM5降噪耳机',
        description: '黑色，旗舰级降噪，音质出色，使用一年，功能正常。',
        price: 1599,
        category_id: 9,
        status: 'on_sale',
        images: JSON.stringify(['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400']),
        contact_phone: '135****5555',
        contact_wechat: 'audio_seller',
        view_count: 145,
        favorite_count: 28,
        user_id: 5,
        created_at: '2024-01-11 11:30:00',
        username: '音乐发烧友',
        nickname: '小张',
        avatar: '',
        category_name: '🎵 音乐乐器'
    },
    {
        id: 6,
        title: 'Switch游戏机 续航版',
        description: '红蓝配色，带128GB内存卡，包含5款热门游戏，几乎全新。',
        price: 1999,
        category_id: 4,
        status: 'on_sale',
        images: JSON.stringify(['https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=400']),
        contact_phone: '134****4444',
        contact_wechat: 'game_seller',
        view_count: 178,
        favorite_count: 35,
        user_id: 6,
        created_at: '2024-01-10 16:20:00',
        username: '游戏达人',
        nickname: '小王',
        avatar: '',
        category_name: '🎮 游戏娱乐'
    }
];

const mockCategories = [
    { id: 1, name: '📚 教材教辅', icon: '📚', sort_order: 1 },
    { id: 2, name: '💻 数码产品', icon: '💻', sort_order: 2 },
    { id: 3, name: '📱 手机平板', icon: '📱', sort_order: 3 },
    { id: 4, name: '🎮 游戏娱乐', icon: '🎮', sort_order: 4 },
    { id: 5, name: '👕 服饰鞋包', icon: '👕', sort_order: 5 },
    { id: 6, name: '🚲 出行工具', icon: '🚲', sort_order: 6 },
    { id: 7, name: '🏠 生活用品', icon: '🏠', sort_order: 7 },
    { id: 8, name: '🎵 音乐乐器', icon: '🎵', sort_order: 8 },
    { id: 9, name: '🏸 运动户外', icon: '🏸', sort_order: 9 },
    { id: 10, name: '其他', icon: '📦', sort_order: 10 }
];

module.exports = { mockProducts, mockCategories };